In [1]:
# Step 1: Import required libraries
import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [2]:
iris = load_iris()
X = iris.data         # Features: sepal/petal length & width (4 values)
y = iris.target       # Labels: 0, 1, 2 (setosa, versicolor, virginica)
y_encoded = to_categorical(y)  # Converts 0 → [1,0,0], 1 → [0,1,0], etc.

X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

In [4]:
model = Sequential()
model.add(Dense(8, input_shape=(4,), activation='relu'))
model.add(Dense(3, activation='softmax'))

In [5]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [6]:
model.fit(X_train, y_train, epochs=100, batch_size=5, verbose=1)

Epoch 1/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.3963 - loss: 1.6329
Epoch 2/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4039 - loss: 1.5345 
Epoch 3/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5281 - loss: 1.3933 
Epoch 4/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5887 - loss: 1.1691 
Epoch 5/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4279 - loss: 1.1650 
Epoch 6/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3682 - loss: 1.1139 
Epoch 7/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3642 - loss: 1.0857 
Epoch 8/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1419 - loss: 1.1019 
Epoch 9/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.2005 - loss: 1.0554 
Epoch 10/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3587 - loss: 1.0342 
Epoch 11/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3322 - loss: 1.0073 
Epoch 12/100
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step -

In [7]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy:.2f}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step - accuracy: 0.9667 - loss: 0.3309
Test Accuracy: 0.97


In [8]:
predictions = model.predict(X_test)
print(predictions)
#print(y_test)
predicted_classes = np.argmax(predictions, axis=1)
print(predicted_classes)
actual_classes = np.argmax(y_test, axis=1)
print(actual_classes)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
[[6.7587118e-03 6.1603361e-01 3.7720761e-01]
 [9.7116041e-01 2.7701003e-02 1.1386344e-03]
 [9.3297494e-06 1.7789409e-01 8.2209653e-01]
 [1.0535875e-02 5.5519915e-01 4.3426487e-01]
 [3.8626641e-03 5.6750637e-01 4.2863089e-01]
 [9.5696050e-01 4.0621560e-02 2.4179532e-03]
 [7.6316625e-02 6.2383544e-01 2.9984790e-01]
 [1.9039923e-03 3.3216223e-01 6.6593373e-01]
 [1.7689805e-03 4.4254300e-01 5.5568796e-01]
 [2.7816540e-02 6.3660866e-01 3.3557481e-01]
 [3.7216372e-03 4.2510027e-01 5.7117808e-01]
 [9.3827081e-01 5.8454484e-02 3.2747728e-03]
 [9.7562367e-01 2.3424659e-02 9.5160329e-04]
 [9.3792754e-01 5.8928207e-02 3.1442398e-03]
 [9.7174370e-01 2.7033810e-02 1.2225095e-03]
 [1.5675781e-02 5.8235735e-01 4.0196684e-01]
 [4.2812870e-04 2.8917444e-01 7.1039736e-01]
 [1.9868143e-02 6.3356137e-01 3.4657055e-01]
 [1.0548794e-02 5.9048843e-01 3.9896277e-01]
 [3.9475551e-04 2.7143785e-01 7.2816730e-01]
 [9.4167906e-01 5.5066198e-02 3.2547854e-03]
 [4.5695417e-03 4

In [9]:
import numpy as np
from sklearn.datasets import load_digits
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Step 1: Load the digits dataset
digits = load_digits()
X = digits.data  # Features (8x8 images flattened into 64 features)
y = digits.target  # Labels (0-9)

# Step 2: Preprocess the data
# Scale the features so that they are in the range [0, 1]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Convert labels to one-hot encoded format
y_one_hot = to_categorical(y, 10)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_one_hot, test_size=0.2, random_state=42)

# Step 3: Define the ANN model
model = Sequential()

# Input layer: Flatten the 64 features into 1D (though it's already 1D, so no need to reshape)
model.add(Dense(64, input_dim=64, activation='relu'))  # First hidden layer with 64 neurons
model.add(Dense(32, activation='relu'))  # Second hidden layer with 32 neurons
model.add(Dense(10, activation='softmax'))  # Output layer with 10 neurons for digits 0-9

# Step 4: Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Step 5: Train the model
model.fit(X_train, y_train, epochs=20, batch_size=32, verbose=1)

# Step 6: Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {accuracy:.4f}")

# Step 7: Make predictions
predictions = model.predict(X_test)
predicted_classes = np.argmax(predictions, axis=1)
actual_classes = np.argmax(y_test, axis=1)

# Show some predictions
for i in range(5):
    print(f"Predicted: {predicted_classes[i]}, Actual: {actual_classes[i]}")


Epoch 1/20


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


45/45 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.3248 - loss: 2.1114
Epoch 2/20
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7095 - loss: 1.0804
Epoch 3/20
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8791 - loss: 0.5631
Epoch 4/20
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9328 - loss: 0.3347
Epoch 5/20
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9578 - loss: 0.2239
Epoch 6/20
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9727 - loss: 0.1462
Epoch 7/20
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9846 - loss: 0.1050
Epoch 8/20
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9920 - loss: 0.0814
Epoch 9/20
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9884 - loss: 0.0752
Epoch 10/20
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9932 - loss: 0.0547
Epoch 11/20
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9954 - loss: 0.0437
Epoch 12/20
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9974 - loss: 0.0343
